### ISSUE TITLE
Filter fusion files based on the gene expression

### ISSUE THREAD

**Issue by zzgeng** [d3b-center/d3b-hope-cohort-analysis#26]
Filter fusion files based on the gene expression with `Integer threshold of expression for both gene in fusion  partners with TPM<1`. Shown as in scripts below. 

https://github.com/d3b-center/OpenPedCan-analysis/blob/dev/analyses/fusion_filtering/02-fusion-filtering.R
https://github.com/d3b-center/annoFuse/blob/master/R/expression_filter_fusion.R

**Comment by jharenza** [comment]
completed in #35
